apiVersion: v1
kind: Service
metadata:
  name: license-service
spec:
  type: ClusterIP
  selector: { app: license-service, role: web }   # web pods only
  ports:
    - port: 3000
      targetPort: 3000
